{
    "success": true,
        "module_name": "SAT English - First Module",
            "total_marks": 330,
                "Total_Questions": 27,
                    "session_id": "448aece5-cdd7-4929-93d4-a284e0b0ade2",
                        "questions": [
                            {
                                "Question_No": 1,
                                "id": "06db7d84-8c30-47a2-a729-be2cc669420a",
                                "Stem": "<p>The number of dark spots that appear on the Sun, known as sunspots, can vary greatly. For example, there were about 180 sunspots in November 2001. <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> there were only about 2 sunspots in December 2008.</p>\n<p>&nbsp;</p>",
                                "Question": "<p>Which choice completes the text with the most logical transition?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "D",
                                "OptionA": "<p>A. &nbsp;In other words,</p>",
                                "OptionB": "<p>B. Similarly,</p>",
                                "OptionC": "<p>C. Therefore,</p>",
                                "OptionD": "<p>D. By comparison,</p>"
                            },
                            {
                                "Question_No": 2,
                                "id": "03008a0f-29a4-4b9d-9d76-dd2c16a068b2",
                                "Stem": "<p>While researching a topic, a student has taken the following notes:</p>\n<ul>\n<li>In the early 1900s, suffragists organized marches for women&rsquo;s voting rights.</li>\n<li>Suffragists in the United Kingdom marched from Edinburgh to London.</li>\n<li>This march began on October 12, 1912, and ended on November 16, 1912.</li>\n<li>Suffragists in the United States marched from New York City to Albany, New York.</li>\n<li>This march began on December 16, 1912, and ended on December 28, 1912.</li>\n</ul>",
                                "Question": "<p>The student wants to emphasize the order in which the two marches occurred. Which choice most effectively uses relevant information from the notes to accomplish this goal?</p>",
                                "Difficulty": "Medium",
                                "marks": 15,
                                "Correct_answer": "A",
                                "OptionA": "<p>A. After suffragists in the UK marched from Edinburgh to London, suffragists in the US marched from New York City to Albany, New York.&nbsp;</p>",
                                "OptionB": "<p>B. In the early 1900s, suffragists in the UK and the US marched for women&rsquo;s voting rights.</p>",
                                "OptionC": "<p>C. A march from New York City to Albany, New York, was followed by one that began in Edinburgh and ended in London. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>",
                                "OptionD": "<p>D. From October 12 to November 16, 1912, suffragists in the UK marched from Edinburgh to London.</p>"
                            },
                            {
                                "Question_No": 3,
                                "id": "0406450d-e748-466e-b552-80bdcbb3c337",
                                "Stem": "<p><em>King Lear</em> is a circa 1606 play by William Shakespeare. In the play, the character of King Lear attempts to test his three daughters&rsquo; devotion to him. He later expresses regret for his actions, as is evident when he <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span></p>",
                                "Question": "<p>Which choice most effectively uses a quotation from <em>King Lear </em>to illustrate the claim?</p>",
                                "Difficulty": "Hard",
                                "marks": 20,
                                "Correct_answer": "C",
                                "OptionA": "<p>A. says of himself, &ldquo;I am a man / more sinned against than sinning.&rdquo;</p>",
                                "OptionB": "<p>B. says during a growing storm, &ldquo;This tempest will not give me leave to ponder / On things would hurt me more.&rdquo;</p>",
                                "OptionC": "<p>C. says to himself while striking his head, &ldquo;Beat at this gate that let thy folly in / And thy dear judgement out!&rdquo;</p>",
                                "OptionD": "<p>D. says of himself, &ldquo;I will do such things&mdash; / What they are yet, I know not; but they shall be / The terrors of the earth!&rdquo;</p>"
                            },
                            {
                                "Question_No": 4,
                                "id": "02d67d00-c164-4fcf-b674-398fee6a4f5f",
                                "Stem": "<p>For her 2021 art installation <em>Anthem</em>, Wu Tsang joined forces with singer and composer Beverly Glenn-Copeland to produce a piece that critics found truly <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span>: they praised Tsang for creatively transforming a museum rotunda into a dynamic exhibit by projecting filmed images of Glenn-Copeland onto a massive 84-foot curtain and filling the space with the sounds of his and other voices singing.</p>",
                                "Question": "<p>Which choice completes the text with the most logical and precise word or phrase?</p>",
                                "Difficulty": "Hard",
                                "marks": 20,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. restrained</p>",
                                "OptionB": "<p>B. inventive</p>",
                                "OptionC": "<p>C. inexplicable</p>",
                                "OptionD": "<p>D. mystifying</p>"
                            },
                            {
                                "Question_No": 5,
                                "id": "011acb8b-438a-4bd2-b9df-8ad2e1ad246b",
                                "Stem": "<p>American fashion designer Patrick Kelly was known for his love of colorful buttons. Many of his signature dresses feature bold assortments of buttons throughout the garment. In a paper, a fashion design student claims that Kelly&rsquo;s use of buttons as decoration was inspired by his childhood observations of the styles and actions of the women in his family.</p>",
                                "Question": "<p>Which quotation from a work by a historian would be the most effective evidence for the student to include in support of this claim?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "C",
                                "OptionA": "<p>A. &ldquo;Although some of the assortments of buttons appear to be mismatched pieces scattered randomly throughout Kelly&rsquo;s dresses, his most famous designs feature carefully crafted patterns of matching buttons.&rdquo;</p>",
                                "OptionB": "<p>B. &ldquo;Many of Kelly&rsquo;s contemporaries were inspired by his designs to incorporate buttons, as well as zippers and snaps, as decorative items in their work.&rdquo;&nbsp;</p>",
                                "OptionC": "<p>C. &ldquo;Kelly&rsquo;s grandmother, who would repair clothing when he was a child, frequently added mismatched buttons to the clothes to draw attention away from any flaws in the garments.&rdquo;</p>",
                                "OptionD": "<p>D. &ldquo;Kelly was destined to be a designer from a young age: he learned how to sew clothing from his aunt Bertha, and his love of drawing was developed by his mother.&rdquo;</p>"
                            },
                            {
                                "Question_No": 6,
                                "id": "01f50c32-789e-42db-a383-6c2c7e6a8a01",
                                "Stem": "<p>While researching a topic, a student has taken the following notes:</p>\n<ul>\n<li>Started in 1925, the Scripps National Spelling Bee is a US-based spelling competition.</li>\n<li>The words used in the competition have diverse linguistic origins.</li>\n<li>In 2008, Sameer Mishra won by correctly spelling the word &ldquo;guerdon.&rdquo;</li>\n<li>&ldquo;Guerdon&rdquo; derives from the Anglo-French word &ldquo;guerdun.&rdquo;</li>\n<li>In 2009, Kavya Shivashankar won by correctly spelling the word &ldquo;Laodicean.&rdquo;</li>\n<li>&ldquo;Laodicean&rdquo; derives from the ancient Greek word &ldquo;<span lang=\"grc\">Laod&iacute;keia.</span>&rdquo;</li>\n</ul>",
                                "Question": "<p>The student wants to emphasize a difference in the origins of the two words. Which choice most effectively uses relevant information from the notes to accomplish this goal?</p>",
                                "Difficulty": "Medium",
                                "marks": 15,
                                "Correct_answer": "A",
                                "OptionA": "<p>A. &ldquo;Guerdon,&rdquo; the final word of the 2008 Scripps National Spelling Bee, is of Anglo-French origin, while the following year&rsquo;s final word, &ldquo;Laodicean,&rdquo; derives from ancient Greek.</p>",
                                "OptionB": "<p>B. In 2008, Sameer Mishra won the Scripps National Spelling Bee by correctly spelling the word &ldquo;guerdon&rdquo;; however, the following year, Kavya Shivashankar won based on spelling the word &ldquo;Laodicean.&rdquo;</p>",
                                "OptionC": "<p>C. Kavya Shivashankar won the 2009 Scripps National Spelling Bee by correctly spelling &ldquo;Laodicean,&rdquo; which derives from the ancient Greek word &ldquo;<span lang=\"grc\">Laod&iacute;keia.</span>&rdquo;</p>",
                                "OptionD": "<p>D. The Scripps National Spelling Bee uses words from diverse linguistic origins, such as &ldquo;guerdon&rdquo; and &ldquo;Laodicean.&rdquo;</p>"
                            },
                            {
                                "Question_No": 7,
                                "id": "00b54c96-3e64-4136-bbba-a169aa0937dc",
                                "Stem": "<p>The following text is adapted from Louisa May Alcott&rsquo;s 1869 novel <em>An Old-Fashioned Girl</em>. Polly, a teenager, is visiting her friend Fanny.</p>\n<blockquote>\n<p>Fanny&rsquo;s friends did not interest Polly much; she was rather afraid of them [because] they seemed so much older and wiser than herself, even those younger in years. They talked about things of which she knew nothing and when Fanny tried to explain, she didn&rsquo;t find them interesting; indeed, some of them rather shocked and puzzled her.</p>\n</blockquote>",
                                "Question": "<p>Which choice best states the main purpose of the text?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "A",
                                "OptionA": "<p>A. To portray Polly&rsquo;s reaction to Fanny&rsquo;s friends</p>",
                                "OptionB": "<p>B. To identify the topics Polly talks about with Fanny&rsquo;s friends</p>",
                                "OptionC": "<p>C. To explain how Fanny met some of her friends</p>",
                                "OptionD": "<p>D. To illustrate how Fanny&rsquo;s friends feel about Polly</p>"
                            },
                            {
                                "Question_No": 8,
                                "id": "058d0cc2-16f9-4b52-8c38-c8a6e0993375",
                                "Stem": "<p>Louise Bennett (1919&ndash;2006), also known as &ldquo;Miss Lou,&rdquo; was an influential Jamaican poet and folklorist. Her innovative poems <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> the use of Jamaican Creole (a spoken language) in literature.</p>",
                                "Question": "<p>Which choice completes the text so that it conforms to the conventions of Standard English?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "C",
                                "OptionA": "<p>A. popularized;&nbsp;</p>",
                                "OptionB": "<p>B. popularized,</p>",
                                "OptionC": "<p>C. popularized</p>",
                                "OptionD": "<p>D. popularized:</p>"
                            },
                            {
                                "Question_No": 9,
                                "id": "06bf3d2d-6ff8-443b-8215-5022a02495cb",
                                "Stem": "<p>Richard Spikes was a prolific African American inventor known for his contributions to automotive engineering. Between 1907 and 1946, he patented many inventions, <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> an automobile turn signal, a safety brake, and&mdash;most famously&mdash;the first automatic gearshift.</p>",
                                "Question": "<p>Which choice completes the text so that it conforms to the conventions of Standard English?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "C",
                                "OptionA": "<p>A. included</p>",
                                "OptionB": "<p>B. includes</p>",
                                "OptionC": "<p>C. including</p>",
                                "OptionD": "<p>D. will include</p>"
                            },
                            {
                                "Question_No": 10,
                                "id": "031f8875-3da8-4cf3-aca1-05369f8c1c0b",
                                "Stem": "<p>While researching a topic, a student has taken the following notes:</p>\n<ul>\n<li>The International Center for the Arts of the Americas (ICAA) is directed by Mari Carmen Ram&iacute;rez.</li>\n<li>Ram&iacute;rez oversaw an initiative to create an online archive of historical documents related to the history of Latin American and Latino visual art.</li>\n<li>The ICAA digitized over 10,000 documents, including the writings of Latin American and Latino artists and critics.</li>\n<li>The creation of the archive didn&rsquo;t require historical documents to be removed from their countries of origin.</li>\n<li>Scholars now have more access to these documents.</li>\n</ul>",
                                "Question": "<p>The student wants to explain an advantage of the ICAA&rsquo;s archive being digital. Which choice most effectively uses relevant information from the notes to accomplish this goal?</p>",
                                "Difficulty": "Medium",
                                "marks": 15,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. Over 10,000 documents related to the history of Latin American and Latino visual art are part of the ICAA archive.</p>",
                                "OptionB": "<p>B. By offering online versions of historical documents, the ICAA&rsquo;s archive provides more access to these materials without removing them from their countries of origin.</p>",
                                "OptionC": "<p>C. Among the historical documents in the ICAA&rsquo;s archive are the writings of Latin American and Latino artists and critics.</p>",
                                "OptionD": "<p>D. The ICAA&rsquo;s director, Mari Carmen Ram&iacute;rez, oversaw the creation of an online archive of historical documents related to Latin American and Latino visual art.</p>"
                            },
                            {
                                "Question_No": 11,
                                "id": "04d1bb44-4a37-4674-b6d5-0dfe9a45e7aa",
                                "Stem": "<p><figure class=\"table\"><table class=\"gdr\"><caption style=\"caption-side: top;\"><p style=\"text-align: center;\">Ablation Rates for Three Elements in Cosmic Dust, by Dust Source</p></caption><thead><tr><th scope=\"col\" style=\"text-align: center; vertical-align: bottom;\">Element</th><th scope=\"col\" style=\"text-align: center; vertical-align: bottom;\">SPC</th><th scope=\"col\" style=\"text-align: center; vertical-align: bottom;\">AST</th><th scope=\"col\" style=\"text-align: center; vertical-align: bottom;\">HTC</th><th scope=\"col\" style=\"text-align: center; vertical-align: bottom;\">OCC</th></tr></thead><tbody><tr><th scope=\"row\" style=\"text-align: left;\">iron</th><td style=\"text-align: center;\">20%</td><td style=\"text-align: center;\">28%</td><td style=\"text-align: center;\">90%</td><td style=\"text-align: center;\">98%</td></tr><tr><th scope=\"row\" style=\"text-align: left;\">potassium</th><td style=\"text-align: center;\">44%</td><td style=\"text-align: center;\">74%</td><td style=\"text-align: center;\">97%</td><td style=\"text-align: center;\">100%</td></tr><tr><th scope=\"row\" style=\"text-align: left;\">sodium</th><td style=\"text-align: center;\">45%</td><td style=\"text-align: center;\">75%</td><td style=\"text-align: center;\">99%</td><td style=\"text-align: center;\">100%</td></tr></tbody></table></figure></p>\n<p>Earth&rsquo;s atmosphere is bombarded by cosmic dust originating from several sources: short-period comets (SPCs), particles from the asteroid belt (ASTs), Halley-type comets (HTCs), and Oort cloud comets (OCCs). Some of the dust&rsquo;s material vaporizes in the atmosphere in a process called ablation, and the faster the particles move, the higher the rate of ablation. Astrophysicist Juan Diego Carrillo-S&aacute;nchez led a team that calculated average ablation rates for elements in the dust (such as iron and potassium) and showed that material in slower-moving SPC or AST dust has a lower rate than the same material in faster-moving HTC or OCC dust. For example, whereas the average ablation rate for iron from AST dust is 28%, the average rate for <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span>&nbsp;</p>",
                                "Question": "<p>Which choice most effectively uses data from the table to complete the example?</p>",
                                "Difficulty": "Hard",
                                "marks": 20,
                                "Correct_answer": "C",
                                "OptionA": "<p>A. iron from SPC dust is 20%.</p>",
                                "OptionB": "<p>B. sodium from OCC dust is 100%.</p>",
                                "OptionC": "<p>C. iron from HTC dust is 90%.</p>",
                                "OptionD": "<p>D. sodium from AST dust is 75%.</p>"
                            },
                            {
                                "Question_No": 12,
                                "id": "041c0cde-3c02-4883-9f71-e15f5836d55f",
                                "Stem": "<p>In her book <em>The Woman Warrior: Memoirs of a Girlhood Among Ghosts</em>, author Maxine Hong Kingston examines themes <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> childhood, womanhood, and Chinese American identity by intertwining autobiography and mythology.</p>",
                                "Question": "<p>Which choice completes the text so that it conforms to the conventions of Standard English?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. of:</p>",
                                "OptionB": "<p>B. &nbsp;of</p>",
                                "OptionC": "<p>C. of&mdash;</p>",
                                "OptionD": "<p>D. of,</p>"
                            },
                            {
                                "Question_No": 13,
                                "id": "06a81789-efdb-490f-8fc3-db5fc5358df3",
                                "Stem": "<p>Like other tribal nations, the Muscogee (Creek) Nation is self-governing; its National Council generates laws regulating aspects of community life such as land use and healthcare, while the principal chief and cabinet officials <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> those laws by devising policies and administering services in accordance with them.</p>",
                                "Question": "<p>Which choice completes the text with the most logical and precise word or phrase?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "A",
                                "OptionA": "<p>A. implement</p>",
                                "OptionB": "<p>B. presume</p>",
                                "OptionC": "<p>C. improvise</p>",
                                "OptionD": "<p>D. mimic</p>"
                            },
                            {
                                "Question_No": 14,
                                "id": "07cc1994-5689-45f6-8ec9-9652e6bca335",
                                "Stem": "<p>The following text is from Bram Stoker&rsquo;s 1897 novel <em>Dracula</em>. The narrator is being driven in a carriage through a remote region at night.</p>\n<blockquote>\n<p>The baying of the wolves sounded nearer and nearer, as though they were closing round on us from every side. I grew dreadfully afraid, and the horses shared my fear. The driver, however, was not in the least <span role=\"region\" aria-label=\"Referenced Content\"><u>disturbed</u></span>; he kept turning his head to left and right, but I could not see anything through the darkness.</p>\n</blockquote>",
                                "Question": "<p>As used in the text, what does the word &ldquo;disturbed&rdquo; most nearly mean?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. Disorganized</p>",
                                "OptionB": "<p>B. Alarmed</p>",
                                "OptionC": "<p>C. Offended</p>",
                                "OptionD": "<p>D. Interrupted</p>"
                            },
                            {
                                "Question_No": 15,
                                "id": "0038f8c3-6235-4272-ac64-4da6c286fc2c",
                                "Stem": "<p>Researchers believe that pieces of hull found off Oregon&rsquo;s coast are from a Spanish cargo ship that was lost in 1697. Stories passed down among the area&rsquo;s Confederated Tribes of Siletz Indians support this belief. <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> Siletz stories describe how blocks of beeswax, an item the ship had been carrying, began washing ashore after the ship was lost.&nbsp;</p>",
                                "Question": "<p>Which choice completes the text with the most logical transition?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. For this reason,</p>",
                                "OptionB": "<p>B. For example,</p>",
                                "OptionC": "<p>C. However,</p>",
                                "OptionD": "<p>D. Likewise,</p>"
                            },
                            {
                                "Question_No": 16,
                                "id": "03b58b2d-ef3a-4927-8278-0d3a50ddbdd1",
                                "Stem": "<p>Archaeologists have been debating the origin of a rare form of lead found in Shang dynasty (1766&ndash;1046 BCE) bronze artifacts since its presence was discovered in China in the 1990s. Different researchers have proposed theories on which regions of the world would have had the raw materials containing the specific lead in these artifacts, but no conclusive evidence has been presented. What is intriguing is that bronze artifacts from China dated after the Shang dynasty do not contain this form of lead, suggesting that <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span></p>",
                                "Question": "<p>Which choice most logically completes the text?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. Shang dynasty bronze pieces are rare and therefore more valuable than those from other time periods.</p>",
                                "OptionB": "<p>B. the source of some of the raw materials used to make bronze was exploited only until the end of the Shang dynasty.</p>",
                                "OptionC": "<p>C. bronze was used for a short time during the Shang dynasty before different metals were used to make artifacts.</p>",
                                "OptionD": "<p>D. methods used to analyze bronze artifacts are not useful on pieces that are dated after the Shang dynasty.</p>"
                            },
                            {
                                "Question_No": 17,
                                "id": "06547b42-1fec-41a9-8c7d-3ad1d3bbca86",
                                "Stem": "<p>A musician and member of the Quechua of Peru, Renata Flores Rivera was eager to promote the Quechua language in her music, but she was <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> speaking it. She met this challenge by asking her grandmother, a native speaker of Quechua, to help her pronounce words in her song lyrics and also by taking classes in the language.</p>",
                                "Question": "<p>Which choice completes the text with the most logical and precise word or phrase?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. prepared for</p>",
                                "OptionB": "<p>B. inexperienced with</p>",
                                "OptionC": "<p>C. skilled in</p>",
                                "OptionD": "<p>D. excited about</p>"
                            },
                            {
                                "Question_No": 18,
                                "id": "06418318-048f-4310-9a6a-078b14e747af",
                                "Stem": "<p>Hip-hop pedagogy is a form of teaching that&rsquo;s gaining popularity across school subjects. It involves incorporating hip-hop and rap music into lessons as well as using hip-hop elements when teaching other subject matters. For example, Quan Neloms&rsquo;s students look for college-level vocabulary and historical events in rap songs. Researchers claim that in addition to developing students&rsquo; social justice awareness, <span role=\"region\" aria-label=\"Referenced Content\"><u>hip-hop pedagogy encourages student success by raising students&rsquo; interest and engagement.</u></span></p>",
                                "Question": "<p>Which finding, if true, would most strongly support the underlined claim?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "D",
                                "OptionA": "<p>A. Students tend to be more enthusiastic about rap music than they are about hip-hop music.</p>",
                                "OptionB": "<p>B. Students who are highly interested in social justice issues typically don&rsquo;t sign up for courses that incorporate hip-hop and rap music.</p>",
                                "OptionC": "<p>C. Educators report that they enjoy teaching courses that involve hip-hop and rap music more than teaching courses that don&rsquo;t.</p>",
                                "OptionD": "<p>D. Courses that incorporate hip-hop and rap music are among the courses with the highest enrollment and attendance rates.</p>"
                            },
                            {
                                "Question_No": 19,
                                "id": "082e64fe-666c-49a6-9c98-2b8d08d78a7d",
                                "Stem": "<p>Although critics believed that customers would never agree to pay to pick their own produce on farms, such concerns didn&rsquo;t <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> Booker T. Whatley&rsquo;s efforts to promote the practice. Thanks in part to Whatley&rsquo;s determined advocacy, farms that allow visitors to pick their own apples, pumpkins, and other produce can be found throughout the United States.</p>",
                                "Question": "<p>Which choice completes the text with the most logical and precise word or phrase?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. enhance</p>",
                                "OptionB": "<p>B. hinder</p>",
                                "OptionC": "<p>C. misrepresent</p>",
                                "OptionD": "<p>D. aggravate</p>"
                            },
                            {
                                "Question_No": 20,
                                "id": "046a49c8-50c7-4b5d-a559-c64f4584bd75",
                                "Stem": "<p>Many Samoans enjoy a sport called kilikiti. This bat-and-ball game was derived from <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> kilikiti differs from cricket in a few key ways.</p>",
                                "Question": "<p>Which choice completes the text so that it conforms to the conventions of Standard English?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "C",
                                "OptionA": "<p>A. cricket but:</p>",
                                "OptionB": "<p>B. cricket but,</p>",
                                "OptionC": "<p>C. cricket, but</p>",
                                "OptionD": "<p>D. cricket, but,</p>"
                            },
                            {
                                "Question_No": 21,
                                "id": "00ba471c-7ba9-4418-a11e-4ea09eb00c47",
                                "Stem": "<p>Roasted green chiles are a popular ingredient in Southwestern cuisine, but the traditional roasting method of burning propane is not environmentally friendly. To see if solar power could provide a better alternative, engineer Kenneth Armijo and his team roasted batches of green chiles using between 38 and 42 heliostats, which are devices that concentrate sunlight. The team was successful in reaching the same roasting temperature used in traditional propane roasting, but they found that propane yielded faster results. While the fastest solar-roasted green chiles took six minutes, batches using propane took only four. Armijo hypothesizes that they can reduce the roasting time for solar-roasted green chiles by using more heliostats.&nbsp;</p>",
                                "Question": "<p>Which finding, if true, would most directly support Armijo&rsquo;s hypothesis?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. The temperature inside the roasting drum is distributed more evenly when roasting green chiles with solar power than with propane.</p>",
                                "OptionB": "<p>B. Attempts to roast green chiles using 50 heliostats yields results in fewer than six minutes.</p>",
                                "OptionC": "<p>C. Green chile connoisseurs prefer the flavor of solar-roasted green chiles over the flavor of propane-roasted green chiles.</p>",
                                "OptionD": "<p>D. The skins of solar-roasted green chiles are easier to peel than the skins of propane-roasted green chiles.</p>"
                            },
                            {
                                "Question_No": 22,
                                "id": "02267f61-527e-4534-a2b4-febe822f4a3f",
                                "Stem": "<p>Works of moral philosophy, such as Plato&rsquo;s <em>Republic</em> or Aristotle&rsquo;s <em>Nicomachean Ethics</em>, are partly concerned with how to live a morally good life. But philosopher Jonathan Barnes argues that works that present a method of living such a life without also supplying a motive are inherently useful only to those already wishing to be morally good&mdash;those with no desire for moral goodness will not choose to follow their rules. However, some works of moral philosophy attempt to describe what constitutes a morally good life while also proposing reasons for living one.</p>",
                                "Question": "<p>Which choice best describes the overall structure of the text?</p>",
                                "Difficulty": "Medium",
                                "marks": 15,
                                "Correct_answer": "A",
                                "OptionA": "<p>A. It provides a characterization about a field of thought by noting two works in it and then details a way in which some works in that field are more comprehensive than others.</p>",
                                "OptionB": "<p>B. It mentions two renowned works and then claims that despite their popularity it is impossible for these works to serve the purpose their authors intended.</p>",
                                "OptionC": "<p>C. It summarizes the history of a field of thought by discussing two works and then proposes a topic of further research for specialists in that field.</p>",
                                "OptionD": "<p>D. It describes two influential works and then explains why one is more widely read than the other.</p>"
                            },
                            {
                                "Question_No": 23,
                                "id": "034f08c6-2e6a-49ec-aeeb-7d7327251e21",
                                "Stem": "<p>The following text is adapted from Elizabeth von Arnim&rsquo;s 1922 novel <em>The Enchanted April</em>. Mrs. Wilkins and her friend Rose are traveling in Italy.</p>\n<blockquote>\n<p>&ldquo;I&rsquo;m going to have one of these gorgeous oranges,&rdquo; said Mrs. Wilkins, staying where she was and <span role=\"region\" aria-label=\"Referenced Content\"><u>reaching across to</u></span> a black bowl piled with them. &ldquo;Rose, how can you resist them. Look&mdash;have this one. Do have this beauty&mdash;&rdquo; And she held out a big one.</p>\n</blockquote>",
                                "Question": "<p>As used in the text, what does the phrase &ldquo;reaching across to&rdquo; most nearly mean?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "C",
                                "OptionA": "<p>A. Joining with</p>",
                                "OptionB": "<p>B. Gaining on</p>",
                                "OptionC": "<p>C. Stretching toward</p>",
                                "OptionD": "<p>D. Arriving at</p>"
                            },
                            {
                                "Question_No": 24,
                                "id": "03f91502-1fd3-4d93-adfe-a3c339800c72",
                                "Stem": "<p>The printing of Virginia Woolf&rsquo;s novels featured a creative <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span> between Woolf and her sister Vanessa Bell: a talented painter, Bell worked closely with Woolf to create original cover art for most of the novels.</p>",
                                "Question": "<p>Which choice completes the text with the most logical and precise word or phrase?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. rebellion</p>",
                                "OptionB": "<p>B. partnership</p>",
                                "OptionC": "<p>C. discovery</p>",
                                "OptionD": "<p>D. disagreement</p>"
                            },
                            {
                                "Question_No": 25,
                                "id": "01a23acb-3f25-4c96-a118-1b8f0c67e947",
                                "Stem": "<p><figure class=\"table\"><table class=\"gdr\"><caption style=\"caption-side: top;\"><p style=\"text-align: center;\">Land Area Covered by Native Flowering Plants at a Site in Antarctica</p></caption><thead><tr><th scope=\"col\" style=\"text-align: center;vertical-align: bottom;\">Species</th><th scope=\"col\" style=\"text-align: center;vertical-align: bottom;\">Area covered in 2009 (in square meters)</th><th scope=\"col\" style=\"text-align: center;vertical-align: bottom;\">Area covered in 2018 (in square meters)</th><th scope=\"col\" style=\"text-align: center;vertical-align: bottom;\">Percent increase in area covered from 2009 to 2018</th></tr></thead><tbody><tr><th scope=\"row\" style=\"text-align: left;\"><em>Deschampsia antarctica</em></th><td style=\"text-align: center;\">1,230</td><td style=\"text-align: center;\">1,576</td><td style=\"text-align: center;\">28%</td></tr><tr><th scope=\"row\" style=\"text-align: left;\"><em>Colobanthus quitensis</em></th><td style=\"text-align: center;\">6.9</td><td style=\"text-align: center;\">10.7</td><td style=\"text-align: center;\">55%</td></tr></tbody></table></figure></p>\n<p>The only flowering plant species native to Antarctica, <em>Colobanthus quitensis </em>and<em> Deschampsia antarctica</em>&nbsp;grow in places where the earth remains free of ice for much of the year. Botanist Niccoletta Cannone wondered how the warming of Antarctica&rsquo;s climate in recent years had affected these species, so she visited a site in Antarctica, first in 2009 and later in 2018, to count the number of plants growing there. Cannone found that the area of land covered by the two species had significantly expanded during the nine-year period. While both species likely benefited from warming temperatures,<em> Colobanthus quitensis </em><span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span></p>",
                                "Question": "<p>Which choice most effectively uses data from the table to complete the comparison?</p>",
                                "Difficulty": "Medium",
                                "marks": 15,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. suppressed the growth of <em>Deschampsia antarctica</em>, which covered a smaller area of land in 2018 than it had in 2009.</p>",
                                "OptionB": "<p>B. saw a greater expansion than <em>Deschampsia antarctica </em>did, increasing the area of land it covered by more than half.</p>",
                                "OptionC": "<p>C. showed a greater increase in the average size of individual plants than <em>Deschampsia antarctica </em>did.</p>",
                                "OptionD": "<p>D. covered land newly freed from ice at a rate 55% faster than that of <em>Deschampsia antarctica</em>.</p>"
                            },
                            {
                                "Question_No": 26,
                                "id": "01aa8927-a4f4-4023-9c24-1675f13372dd",
                                "Stem": "<p>Although it&rsquo;s clear that Mars once had liquid water on its surface, astronomers have debated whether the evidence of ancient water reflects a prolonged phase of warm, wet conditions&mdash;the so-called wet and warm scenario&mdash;or a brief period of melting in an otherwise consistently frozen environment. Researchers Benjamin T. Cardenas and Michael P. Lamb recently added to this debate by using data from NASA and the Mars Orbiter Laser Altimeter to map the topography of what is now a large basin in Mars&rsquo;s northern hemisphere. Cardenas and Lamb concluded that the wet and warm scenario is likely correct.&nbsp;&nbsp;</p>",
                                "Question": "<p>Which finding about the basin, if true, would most directly support Cardenas and Lamb&rsquo;s conclusion?</p>",
                                "Difficulty": "Medium",
                                "marks": 15,
                                "Correct_answer": "B",
                                "OptionA": "<p>A. Its dimensions and shape indicate that it is unlikely to have formed as the result of an asteroid or comet impact.&nbsp;</p>",
                                "OptionB": "<p>B. It has features suggesting that it once held an ocean that underwent gradual sea-level changes over an extended time.</p>",
                                "OptionC": "<p>C. Its physical characteristics are most consistent with it having formed as a result of a massive but short-lived influx of liquid water.</p>",
                                "OptionD": "<p>D. It is surrounded by channels that could have been formed either by running water or by flowing lava.&nbsp;</p>"
                            },
                            {
                                "Question_No": 27,
                                "id": "081193c5-8ebf-4777-b955-61185e08239c",
                                "Stem": "<p>Off-off-Broadway theaters emerged in the late 1950s as a rebellion against mainstream Broadway theaters in New York, freeing artists to create productions that were more experimental than typical Broadway shows. One such artist was playwright Mar&iacute;a Irene Forn&eacute;s. Working with off-off Broadway theaters enabled Forn&eacute;s not only to direct her own plays but also to direct them exactly as she intended them to be staged, regardless of how strange the results might have seemed to audiences accustomed to Broadway shows. In this way, Forn&eacute;s <span aria-hidden=\"true\">______</span><span class=\"sr-only\">blank</span></p>",
                                "Question": "<p>Which choice most logically completes the text?</p>",
                                "Difficulty": "Easy",
                                "marks": 10,
                                "Correct_answer": "D",
                                "OptionA": "<p>A. wrote plays that would have been too expensive to produce if someone else had directed the production.</p>",
                                "OptionB": "<p>B. recognized that staging an off-off-Broadway play was more complicated than staging a Broadway play.</p>",
                                "OptionC": "<p>C. would have been more famous if she had created plays that were mainstream instead of experimental.</p>",
                                "OptionD": "<p>D. illustrates the artistic opportunity offered by off-off Broadway theaters.</p>"
                            }
                        ]
}